# -*- coding: utf8 -*-
import re

def country2code(country):
    """
    Get country name and return his code.
    >>> country2code('france')
    'FR'

    >>> country2code('Madagascar')
    'MG'

    >>> country2code(u'S\xe9n\xe9gal')
    'SN'

    >>> country2code('République démocratique du Congo')
    'CG'
    """
    country_dict = dict()
    country_dict['andorre'] = 'AD'
    country_dict['emirats arabes unis'] = 'AE'
    country_dict['afghanistan'] = 'AF'
    country_dict['antigua et barbuda'] = 'AG'
    country_dict['anguilla'] = 'AI'
    country_dict['albanie'] = 'AL'
    country_dict['armenie'] = 'AM'
    country_dict['antilles neerlandaises'] = 'AN'
    country_dict['angola'] = 'AO'
    country_dict['antarctique'] = 'AQ'
    country_dict['argentine'] = 'AR'
    country_dict['samoa americaines'] = 'AS'
    country_dict['autriche'] = 'AT'
    country_dict['australie'] = 'AU'
    country_dict['aruba'] = 'AW'
    country_dict['aland'] = 'AX'
    country_dict['azerbaidjan'] = 'AZ'
    country_dict['bosnie-herzegovine'] = 'BA'
    country_dict['barbade'] = 'BB'
    country_dict['bangladesh'] = 'BD'
    country_dict['belgique'] = 'BE'
    country_dict['burkina faso'] = 'BF'
    country_dict['bulgarie'] = 'BG'
    country_dict['bahrein'] = 'BH'
    country_dict['burundi'] = 'BI'
    country_dict['benin'] = 'BJ'
    country_dict['bermudes'] = 'BM'
    country_dict['brunei darussalam'] = 'BN'
    country_dict['bolivie'] = 'BO'
    country_dict['bresil'] = 'BR'
    country_dict['bahamas'] = 'BS'
    country_dict['bhoutan'] = 'BT'
    country_dict['bouvet'] = 'BV'
    country_dict['botswana'] = 'BW'
    country_dict['belarus'] = 'BY'
    country_dict['belize'] = 'BZ'
    country_dict['canada'] = 'CA'
    country_dict['cocos (keeling)'] = 'CC'
    country_dict['centrafricaine'] = 'CF'
    country_dict['congo'] = 'CG'
    country_dict['suisse'] = 'CH'
    country_dict['côte d\'ivoire'] = 'CI'
    country_dict['cook'] = 'CK'
    country_dict['chili'] = 'CL'
    country_dict['cameroun'] = 'CM'
    country_dict['chine'] = 'CN'
    country_dict['colombie'] = 'CO'
    country_dict['costa rica'] = 'CR'
    country_dict['cuba'] = 'CU'
    country_dict['cap-vert'] = 'CV'
    country_dict['christmas'] = 'CX'
    country_dict['chypre'] = 'CY'
    country_dict['tcheque'] = 'CZ'
    country_dict['allemagne'] = 'DE'
    country_dict['djibouti'] = 'DJ'
    country_dict['danemark'] = 'DK'
    country_dict['dominique'] = 'DM'
    country_dict['dominicaine'] = 'DO'
    country_dict['algerie'] = 'dZ'
    country_dict['equateur'] = 'EC'
    country_dict['estonie'] = 'EE'
    country_dict['egypte'] = 'EG'
    country_dict['sahara occidental'] = 'EH'
    country_dict['erythree'] = 'ER'
    country_dict['espagne'] = 'ES'
    country_dict['ethiopie'] = 'ET'
    country_dict['finlande'] = 'FI'
    country_dict['fidji'] = 'FJ'
    country_dict['falkland'] = 'FK'
    country_dict['micronesie'] = 'FM'
    country_dict['feroe'] = 'FO'
    country_dict['france'] = 'FR'
    country_dict['gabon'] = 'GA'
    country_dict['royaume-uni'] = 'GB'
    country_dict['grenade'] = 'GD'
    country_dict['georgie'] = 'GE'
    country_dict['guyane francaise'] = 'GF'
    country_dict['guernesey'] = 'Gg'
    country_dict['ghana'] = 'GH'
    country_dict['gibraltar'] = 'GI'
    country_dict['groenland'] = 'GL'
    country_dict['gambie'] = 'GM'
    country_dict['guinee'] = 'GN'
    country_dict['guadeloupe'] = 'GP'
    country_dict['guinee equatoriale'] = 'GQ'
    country_dict['grece'] = 'GR'
    country_dict['georgie du sud et les iles sandwich du sud'] = 'GS'
    country_dict['guatemala'] = 'GT'
    country_dict['guam'] = 'GU'
    country_dict['guinee-bissau'] = 'GW'
    country_dict['guyana'] = 'GY'
    country_dict['hong-kong'] = 'HK'
    country_dict['heard'] = 'HM'
    country_dict['honduras'] = 'HN'
    country_dict['croatie'] = 'HR'
    country_dict['haiti'] = 'HT'
    country_dict['hongrie'] = 'HU'
    country_dict['indonesie'] = 'ID'
    country_dict['irlande'] = 'IE'
    country_dict['israël'] = 'IL'
    country_dict['ile de man'] = 'IM'
    country_dict['inde'] = 'IN'
    country_dict['ocean indien'] = 'IO'
    country_dict['iraq'] = 'IQ'
    country_dict['iran'] = 'IR'
    country_dict['islande'] = 'IS'
    country_dict['italie'] = 'IT'
    country_dict['jersey'] = 'JE'
    country_dict['jamaique'] = 'JM'
    country_dict['jordanie'] = 'JO'
    country_dict['japon'] = 'JP'
    country_dict['kenya'] = 'KE'
    country_dict['kirghizistan'] = 'KG'
    country_dict['cambodge'] = 'kH'
    country_dict['kiribati'] = 'KI'
    country_dict['comores'] = 'kM'
    country_dict['saint-kitts-et-nevis'] = 'KN'
    country_dict['kosovo'] = 'KO'
    country_dict['coree'] = 'kP'
    country_dict['coree'] = 'kR'
    country_dict['koweit'] = 'KW'
    country_dict['caimanes'] = 'kY'
    country_dict['kazakhstan'] = 'KZ'
    country_dict['lao'] = 'LA'
    country_dict['liban'] = 'LB'
    country_dict['sainte-lucie'] = 'LC'
    country_dict['liechtenstein'] = 'LI'
    country_dict['sri lanka'] = 'LK'
    country_dict['liberia'] = 'LR'
    country_dict['lesotho'] = 'LS'
    country_dict['lituanie'] = 'LT'
    country_dict['luxembourg'] = 'LU'
    country_dict['lettonie'] = 'LV'
    country_dict['libyenne'] = 'LY'
    country_dict['maroc'] = 'MA'
    country_dict['monaco'] = 'MC'
    country_dict['moldova'] = 'MD'
    country_dict['montenegro'] = 'ME'
    country_dict['saint-martin'] = 'MF'
    country_dict['madagascar'] = 'MG'
    country_dict['marshall'] = 'MH'
    country_dict['macedoine'] = 'MK'
    country_dict['mali'] = 'ML'
    country_dict['myanmar'] = 'MM'
    country_dict['mongolie'] = 'MN'
    country_dict['macao'] = 'MO'
    country_dict['mariannes du nord'] = 'MP'
    country_dict['martinique'] = 'MQ'
    country_dict['mauritanie'] = 'MR'
    country_dict['montserrat'] = 'MS'
    country_dict['malte'] = 'MT'
    country_dict['maurice'] = 'MU'
    country_dict['maldives'] = 'MV'
    country_dict['malawi'] = 'MW'
    country_dict['mexique'] = 'MX'
    country_dict['malaisie'] = 'MY'
    country_dict['mozambique'] = 'MZ'
    country_dict['namibie'] = 'NA'
    country_dict['nouvelle-caledonie'] = 'NC'
    country_dict['niger'] = 'NE'
    country_dict['norfolk'] = 'NF'
    country_dict['nigeria'] = 'NG'
    country_dict['nicaragua'] = 'NI'
    country_dict['pays-bas'] = 'NL'
    country_dict['norvege'] = 'NO'
    country_dict['nepal'] = 'NP'
    country_dict['nauru'] = 'NR'
    country_dict['niue'] = 'NU'
    country_dict['nouvelle-zelande'] = 'NZ'
    country_dict['oman'] = 'OM'
    country_dict['panama'] = 'PA'
    country_dict['perou'] = 'PE'
    country_dict['polynesie francaise'] = 'PF'
    country_dict['papouasie-nouvelle-guinee'] = 'PG'
    country_dict['philippines'] = 'PH'
    country_dict['pakistan'] = 'PK'
    country_dict['pologne'] = 'PL'
    country_dict['saint-pierre-et-miquelon'] = 'PM'
    country_dict['pitcairn'] = 'PN'
    country_dict['porto rico'] = 'PR'
    country_dict['palestinien occupe'] = 'PS'
    country_dict['portugal'] = 'PT'
    country_dict['palaos'] = 'PW'
    country_dict['paraguay'] = 'PY'
    country_dict['qatar'] = 'QA'
    country_dict['reunion'] = 'RE'
    country_dict['roumanie'] = 'RO'
    country_dict['serbie'] = 'RS'
    country_dict['russie'] = 'RU'
    country_dict['rwanda'] = 'RW'
    country_dict['arabie saoudite'] = 'SA'
    country_dict['salomon'] = 'SB'
    country_dict['seychelles'] = 'SC'
    country_dict['soudan'] = 'SD'
    country_dict['suede'] = 'SE'
    country_dict['singapour'] = 'SG'
    country_dict['sainte-helene'] = 'SH'
    country_dict['slovenie'] = 'SI'
    country_dict['svalbard et ile jan mayen'] = 'SJ'
    country_dict['slovaquie'] = 'SK'
    country_dict['sierra leone'] = 'SL'
    country_dict['saint-marin'] = 'SM'
    country_dict['senegal'] = 'SN'
    country_dict['somalie'] = 'SO'
    country_dict['suriname'] = 'SR'
    country_dict['sao tome-et-principe'] = 'ST'
    country_dict['el salvador'] = 'SV'
    country_dict['syrienne'] = 'SY'
    country_dict['swaziland'] = 'SZ'
    country_dict['turks et caiques'] = 'TC'
    country_dict['tchad'] = 'TD'
    country_dict['terres australes francaises'] = 'TF'
    country_dict['togo'] = 'TG'
    country_dict['thailande'] = 'TH'
    country_dict['tadjikistan'] = 'TJ'
    country_dict['tokelau'] = 'TK'
    country_dict['timor-leste'] = 'TL'
    country_dict['turkmenistan'] = 'TM'
    country_dict['tunisie'] = 'TN'
    country_dict['tonga'] = 'TO'
    country_dict['turquie'] = 'TR'
    country_dict['trinite-et-Tobago'] = 'TT'
    country_dict['tuvalu'] = 'TV'
    country_dict['taiwan'] = 'TW'
    country_dict['tanzanie'] = 'TZ'
    country_dict['ukraine'] = 'UA'
    country_dict['ouganda'] = 'UG'
    country_dict['iles mineures eloignees des etats-unis'] = 'UM'
    country_dict['etats-unis'] = 'US'
    country_dict['uruguay'] = 'UY'
    country_dict['ouzbekistan'] = 'UZ'
    country_dict['vatican'] = 'VA'
    country_dict['saint-vincent-et-les grenadines'] = 'VC'
    country_dict['venezuela'] = 'VE'
    country_dict['iles vierges britanniques'] = 'VG'
    country_dict['iles vierges des etats-unis'] = 'VI'
    country_dict['viet nam'] = 'VN'
    country_dict['vanuatu'] = 'VU'
    country_dict['wallis et futuna'] = 'WF'
    country_dict['samoa'] = 'WS'
    country_dict['yemen'] = 'YE'
    country_dict['mayotte'] = 'YT'
    country_dict['afrique du sud'] = 'ZA'
    country_dict['zambie'] = 'ZM'
    country_dict['zimbabwe'] = 'ZW'

    if country:
        try:
            country = country.replace(" ","-").lower().encode('ASCII', 'replace').replace('?', '.')
        except:
            country = country.replace(" ","-").lower()
        for key,value in country_dict.items():
            if re.search(country, key) or re.search(key, country):
                return value

if __name__ == '__main__':
    import doctest
    doctest.testmod()
